import { useState } from 'react';
import { useConnectionStore } from '../../connection/store/connectionStore.js';
import { useWorkspaceStore } from '../../workspace/store/workspaceStore.js';
import { useMcpStore } from '../store/mcpStore.js';
import type { McpTransport } from '../types/mcp.js';

export function McpPanel() {
  const connection = useConnectionStore(); const workspace = useWorkspaceStore(); const mcps = useMcpStore();
  const [name, setName] = useState(''); const [target, setTarget] = useState(''); const [transport, setTransport] = useState<McpTransport>('stdio');
  const ready = connection.status === 'connected' && workspace.status === 'ready' && Boolean(workspace.path);
  const save = async () => { const next = await mcps.save({ baseUrl: connection.baseUrl, token: connection.token }, workspace.path, workspace.config); if (next) useWorkspaceStore.setState({ config: next }); };
  return <section className="rounded-3xl border border-zinc-800 bg-zinc-950/80 p-6 shadow-2xl shadow-black/30"><div className="mb-5"><p className="text-sm uppercase tracking-[0.3em] text-teal-300">Etapa 9</p><h2 className="mt-2 text-2xl font-semibold text-white">MCPs</h2><p className="mt-2 text-sm text-zinc-400">Configure MCPs declarativos do workspace. Execução real de servidores externos ainda não é iniciada.</p></div><div className="grid gap-3 sm:grid-cols-4"><input className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2 text-white" disabled={!ready} placeholder="nome" value={name} onChange={(e) => setName(e.target.value)} /><select className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2 text-white" disabled={!ready} value={transport} onChange={(e) => setTransport(e.target.value as McpTransport)}><option value="stdio">stdio</option><option value="http">http</option><option value="sse">sse</option></select><input className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2 text-white" disabled={!ready} placeholder={transport === 'stdio' ? 'comando' : 'url'} value={target} onChange={(e) => setTarget(e.target.value)} /><button className="rounded-xl bg-teal-300 px-4 py-2 font-semibold text-zinc-950 disabled:opacity-50" disabled={!ready || !name || !target} onClick={() => { mcps.upsert({ name, transport, enabled: true, command: transport === 'stdio' ? target : undefined, url: transport !== 'stdio' ? target : undefined }); void save(); }} type="button">Adicionar MCP</button></div><div className="mt-4 space-y-2">{mcps.mcps.length === 0 && <p className="text-sm text-zinc-500">Nenhum MCP configurado.</p>}{mcps.mcps.map((mcp) => <article className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-4" key={mcp.name}><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-white">{mcp.name}</h3><p className="text-sm text-zinc-400">{mcp.transport} · {mcp.command ?? mcp.url}</p><p className="text-xs text-zinc-500">Ferramentas: {(mcp.tools ?? []).map((tool) => tool.name).join(', ') || 'nenhuma'}</p></div><label className="text-sm text-zinc-200"><input checked={mcp.enabled} onChange={(event) => mcps.setEnabled(mcp.name, event.target.checked)} type="checkbox" /> habilitado</label></div></article>)}</div>{!ready && <p className="mt-4 text-sm text-zinc-500">Conecte ao serviço e inicialize um workspace para configurar MCPs.</p>}</section>;
}
